const path=require('path')
module.exports={
    mode:"production",
    entry:'./src/New.js',
    output:{
        path:path.resolve(__dirname,'main'),
        filename:"output.js"
    },
    module:{
        rules:[
            {
                test:/\.css$/,
                use:[
                    'style-loader',
                    'css-loader'
                ]
            }
        ]
    }
}
